require("config.lazy")

require("config.options")
require("config.keymaps")

require("plugins.mason")
require("plugins.lspconfig")
require("plugins.nvim-cmp")

require("plugins.auto-close")
require("plugins.colorscheme")
require("plugins.gitsigns")
require("plugins.harpoon")
require("plugins.lualine")
require("plugins.maximize")
require("plugins.neo-tree")
require("plugins.smart-splits")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.vim-fugitive")
require("plugins.vim-surround")
require("plugins.web-dev-icons")
