require("config.lazy")

require("config.options")
require("config.keymaps")

require("plugins.colorscheme")
require("plugins.gitsigns")
require("plugins.harpoon")
require("plugins.lualine")
require("plugins.maximize")
require("plugins.nvim-tree")
require("plugins.nvim-ts-autotag")
require("plugins.smart-splits")
require("plugins.telescope")
require("plugins.vim-fugitive")
require("plugins.vim-surround")
require("plugins.web-dev-icons")
